# Generated by Django 4.1.4 on 2023-01-18 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=255, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='Заголовок'),
        ),
    ]
